name: starwarsproj_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  english_words: ^4.0.0
  provider: ^6.0.0
  logging: ^1.2.0
  get: ^4.6.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/people/
    - assets/images/planets/
    - assets/images/vehicles/
    - assets/images/background/
    - .env
